### ISSUE TITLE
SIS Bugs (5.9.3 and 5.10.1)

### ISSUE THREAD

**Issue by shoy-NOAA** [oceanmapping/community#17]
A couple of bugs were noted with the update of SIS to 5.10.1 (also observed with 5.9.3):

1. In Parameter Setup, though the Logging Interval is set to 3600, the files split at 30 rather than 60 minutes. No restart has been able to effectuate the change.
2. In Parameter Setup, though the Auto Start Echosounder on Start-Up is set to 1, the EM 304 will not auto start.
3. When starting a New Survey, the vessel name will not append to the file name due to a bug.

**Comment by shoy-NOAA** [comment]
To append the Vessel Name to the raw file:

Go to:
C:\ProgramData\Kongsberg Maritime\ksis\
Open
SurveyInfo.ini
beneath Common, edit line:
AppendName=True

**Comment by shoy-NOAA** [comment]
To change the logging interval to 3600s:

Go to:

C:\ProgramData\Kongsberg Maritime\ksis
Open SISTokens.json
find the MAIN_W_LINE_CNT_TIMEOUT variable
change to desired length (3600 for hour lines)
Save and close
Restart SIS to effectuate

**Comment by valschmidt** [comment]
There is a bug in 5.9.3 in which the K-Controller is only listening on the internal "localhost" network interface for receiving operational commands. This breaks any ability to remotely control a sonar from a third-party device which is not running on the same PC as the K-Controller. This is common on autonomous systems. Kongsberg support is aware.
