### ISSUE TITLE
SIS5 issue reading backscatter calibration file Calib124.txt and falsely reporting that it is using the default

### ISSUE THREAD

**Issue by ejheffron** [oceanmapping/community#44]
SIS 5.11.1 Build date 2022-11-11

After replacing the SIS machine, the telnet reported:
Reading backscatter calibration file failed on: Calib124.txt : (4000) Mode: 6 Swath: 2 N sectors: 6 Header parse error:
Followed by: 
** No RX backscatter correction file for head EM 124 . Using default.

We found a copy of the Calib124.txt file and uploaded it to the PU via FTP, but there was still an issue. In the meantime, we were not collecting ANY backscatter -- waterfall display was showing nothing, water column display was showing a purple wedge (aka nothing).

With help from Kongsberg (thanks Jørgen) we discovered that if there is a Calib124.txt file present on the PU and it has issues, the system will NOT use the default backscatter correction file, even though it continues to report that it is via the telnet. In order to get it to use the default, you have to FTP into the PU and rename the Calib124.txt file so it can't find it (broken_Calib124.txt or something). Then it will use the default and you will get backscatter.

Easy enough fix but we lost several hours of data while we got it sorted out. Put this here in the hopes someone else with the issue will be able to fix it more quickly.

**Comment by ejheffron** [comment]
As a follow-up, side-by-side comparison of the Calib124.txt and default file showed an extra line of text that was't commented out under the (commented-out) descriptive info for each mode. No idea how that happened, but fixing it so that the mode info wasn't readable text fixed the Calib124.txt file.

**Comment by ggdp** [comment]
[heart]         Syxinh Le reacted to your message:
________________________________
