### ISSUE TITLE
Large PU-POS difference, wobble in data

### ISSUE THREAD

**Issue by ejheffron** [oceanmapping/community#47]
Documenting a just-resolved issue here.

We noticed a really dramatic wobble in our EM712 data. EM304 data be collected simultaenously did not have any noticeable issues. The wobble varied but at it's worse, it was easy to spot real time in the SIS display, and was very evident in the Qimera surface during processing. The extremeness varied over the course of the survey. We also noticed a really large number in the PU - POS difference in the Numerical Display (red box in SIS display image).
![EM712_Wobble PU-POSerror_Annotated](https://github.com/oceanmapping/community/assets/80911286/937b2f5b-37a4-4e07-9128-4ca94e432ed3)
.

**Comment by ejheffron** [comment]
![Uploading EM712_Wobble&PU-POSerror_Annotated.PNG…]()

**Comment by ejheffron** [comment]
Troubleshooting in the Qimera Wobble Analysis tool showed that applying a pretty large motion latency smoothed out the surface.
![Uploading WobbleAnalysis_initial_0134-0135.PNG…]()

**Comment by ejheffron** [comment]
![WobbleAnalysis_Lines_0134-0135_comparison](https://github.com/oceanmapping/community/assets/80911286/ff01bd37-3344-498e-8268-d35f0471dd85)
![WobbleAnalysis_MotionLatency_5pt2_0134-0135](https://github.com/oceanmapping/community/assets/80911286/394237b3-7fbe-40ba-8f30-b7496c83b213)

**Comment by ejheffron** [comment]
Kongsberg reviewed files and pointed out that the time delay was evident in the datagram viewer
![PU_ClockDeviation_Line0035](https://github.com/oceanmapping/community/assets/80911286/deb019ac-97e9-44e4-94c4-bd9abed9d45d)

**Comment by ejheffron** [comment]
@kjerram also took a look with the swath plotter told us where we can see the time difference info 
![Uploading MRU-SKM time diff files 0035 0047 0058 over three seconds.png…]()

**Comment by ejheffron** [comment]
Additional info from Kongsberg:

We have seen some problems syncing at startup, so after booting look at PU-ZDA/PU-POS, this should always be less than 1000. normally close to 0, but it depends on the Position system.
If it is large, change sync source, then go back to the old syncsource.

As suggested we changed the Time system source in the sensor setup, and then switched it back:
![SwitchThis_ForceTimingReset](https://github.com/oceanmapping/community/assets/80911286/9f096935-9058-4f2e-b3c4-33ac876c6b7a)

This resolved the issue.

**Comment by ejheffron** [comment]
thanks Torgrim, thanks Kevin, issue resolved!

**Comment by kjerram** [comment]
Thanks, @ejheffron! These screenshots are super helpful.
