### ISSUE TITLE
Removing turns in bathymetry and backscatter processing

### ISSUE THREAD

**Issue by kjerram** [oceanmapping/community#48]
Adapted from email conversation between Shannon Hoy (NOAA) and Jonathan Beaudoin (HydroOctave Consulting) in Feb 2024.

**Context:**
Survey files are not incremented during turns, leaving turn data in the files and complicating the 'standard' survey line processing.

**Problem:**
The impacts of swaths in the turns are especially clear and problematic in backscatter mosaics (e.g., in FMGT).

**Various solutions:**

**1. Mosaic editing:**
Remove turn data from mosaics in the backscatter processing software.

_Pro: This does not require earlier processing or export to GSF; the raw data format can be used._

_Con: Edits made to the mosaics are not carried through to other products (e.g., other mosaics at different resolutions).  Also, the swath removal step in backscatter software may be less intuitive / more time-consuming than swath or navigation rejection in other packages (see below)._

**2. Swath editing:**
Remove turn data in bathymetry processing software (e.g., Qimera), export to GSF, and import into backscatter processing software (e.g., FMGT).

_Pro: This provides the opportunity to address other bathymetric data quality issues (e.g., outlier removal) and carries the edit all the way through bathy and backscatter processing._

_Con: This requires swath editing and export to GSF from another software package._

**3. Navigation editing:**
Remove turn data by flagging / rejecting the corresponding heading data in the time series editor (e.g., in Qimera).  This causes a navigation lookup failure during bathy processing that will reject the turning swaths and carry this through to GSF export.
    
_Pro: may be much faster than swath editing; GSF carries these edits through all mosaics in the backscatter processing step._

_Con: This requires navigation editing and export to GSF from another software package._

**Comment by JonathanBeaudoin** [comment]
Thanks for posting this, @kjerram . One fine tuning recommendation: The "Con" for option 3 should mention that this requires navigation editing, not swath editing.
