### ISSUE TITLE
SIS 4 Grid Engine intermittently stopping

### ISSUE THREAD

**Issue by kjerram** [oceanmapping/community#51]
Credit to Liz Ricci (UW) for reporting symptoms and troubleshooting with Kongsberg technical support.

Symptoms:
SIS 4 (EM302) grid engine fails intermittently during survey, making it impossible to monitor real-time gridding in the Geographical window for selecting dredging targets.  The .all files process correctly in other software for producing grids (i.e., there are no issues with the raw data).

Troubleshooting:
No improvement with restarting the grid engine (e.g., using the Restart HDDS button) or making new surveys in SIS.
The only method that has consistently worked to restart gridding is restarting the TRU, SIS, and SIS computer.

Suggestions from Kongsberg:
1. Remove old surveys from the computer and SIS 4.
2. Try different grid cell resolutions when making a survey.

Grid cell sizing for SIS 4 survey parameters (when making a new survey) paraphrased from Tony Dahlheim at Kongsberg:

_Grid cell size should be the maximum expected swath width in meters divided by the resolution. There are several resolutions to choose from (64x64, 128x128, 256x256, 512x512, etc.). Example: The maximum expected swath width is 3500 m for a given survey area (e.g., based on depth and coverage trends for the system).  If we want 64x64 resolution, then 3500 m divided by 64 results in a 55 m grid cell size to enter in the SIS 4 new survey parameters._

Increasing the grid resolution (e.g., up to 512x512) reduces the number of soundings per grid cell but increases the demand on the processor.  When in doubt, try reducing the grid resolution and increasing the grid cell size while making a new survey.

**Comment by kjerram** [comment]
Related Issues:
#7 SIS 5 gridding engine stops permanently
#39 Real-time coverage grid stops updating in Kongsberg SIS

**Comment by cpeters220** [comment]
Hi folks, I would like to make sure we keep SIS4 and SIS5 separate. SIS4 is on LIMITED MAINTENANCE now (see attachment).

[110-0075209a_SIS4-Limited Maintenance.pdf](https://github.com/user-attachments/files/17345118/110-0075209a_SIS4-Limited.Maintenance.pdf)

**Comment by cpeters220** [comment]
closing with Tony's suggestions above.
