### ISSUE TITLE
SIS 5 gridding engine stops permanently

### ISSUE THREAD

**Issue by kjerram** [oceanmapping/community#7]
[Adapted from EX2101 notes / SIS v5.6.0.441]

Symptoms:
1. SIS stops gridding altogether if the grid becomes too large or a portion of it becomes corrupted (e.g., network crash or power loss)

2. Multiple SIS / SIS machine / PU restarts and ‘Restart HDDS’ do not improve / recover the grid

**Comment by shoy-NOAA** [comment]
I have found that once multiple UTM zones are crossed, SIS will stop grinding and a new survey needs to be started. SIS 10.1 seems a lot more reliable with regard to gridding and the Restart GUI WORKS (unlike previous versions)!
